sonar.projectKey=academia.academia.transporteapi
sonar.working.directory=C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia
sonar.pullrequest.cache.basepath=C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi

5CBF7A03-38D2-46E5-886C-7E136ECD501F.sonar.projectKey=academia.academia.transporteapi:5CBF7A03-38D2-46E5-886C-7E136ECD501F
5CBF7A03-38D2-46E5-886C-7E136ECD501F.sonar.projectName=Academia.WebRentas.WebApi
5CBF7A03-38D2-46E5-886C-7E136ECD501F.sonar.projectBaseDir=C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi
5CBF7A03-38D2-46E5-886C-7E136ECD501F.sonar.sourceEncoding=utf-8
5CBF7A03-38D2-46E5-886C-7E136ECD501F.sonar.sources=\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Controllers\\CommonController.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Controllers\\ContratoRentaController.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Controllers\\PagoRentaController.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Controllers\\ProveedorController.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Controllers\\ServicioController.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Controllers\\SucursalController.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\BDRentasContext.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Entities\\Colaborador.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Entities\\ContratoRenta.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Entities\\Documento.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Entities\\LogSincronizacion.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Entities\\Moneda.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Entities\\PagoRenta.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Entities\\Proveedor.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Entities\\Servicio.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Entities\\Sucursal.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Entities\\TasaDeCambio.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Entities\\TipoDocumento.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Maps\\ColaboradorMap.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Maps\\ContratoRentaMap.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Maps\\DocumentoMap.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Maps\\LogSincronizacionMap.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Maps\\MonedaMap.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Maps\\PagoRentaMap.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Maps\\ProveedorMap.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Maps\\ServicioMap.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Maps\\SucursalMap.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Maps\\TasaDeCambioMap.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\BDRentas\\Maps\\TipoDocumentoMap.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Infrastructure\\UnitOfWorkBuilder.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Program.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Common\\AutomapperProfiles.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Common\\CommonService.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Common\\ControllerExtension.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Common\\DomainRequirement\\ContratoRentaDomainRequirement.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Common\\DomainRequirement\\SucursalDomainRequirement.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Common\\Dtos\\ContratoRentaDto\\ActualizarContratoDto.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Common\\Dtos\\ContratoRentaDto\\InactivarContratoDto.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Common\\Dtos\\ContratoRentaDto\\InsertarContratoDto.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Common\\Dtos\\ContratoRentaDto\\ObtenerContratoDto.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Common\\Dtos\\SucursalDto\\ActualizarSucursalDto.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Common\\Dtos\\SucursalDto\\DesactivarSucursalDto.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Common\\Dtos\\SucursalDto\\InsertarSucursalDto.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Common\\Dtos\\SucursalDto\\ObtenerSucursalDTO.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Common\\EnumMensajesError.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Common\\Mensajes.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Common\\PaginacionHelper.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Common\\Service\\IContratoRenta.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Common\\Service\\ISucursal.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Features\\ContratosRenta\\ContratoRentaDomain.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Features\\ContratosRenta\\ContratoRentaService.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Features\\PagoRentas\\PagoRentaService.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Features\\Proveedores\\ProveedorService.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Features\\Servicios\\ServicioService.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Features\\Sucursales\\SucursalDomain.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\_Features\\Sucursales\\SucursalService.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\obj\\Debug\\net8.0\\Academia.WebRentas.WebApi.GlobalUsings.g.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\obj\\Debug\\net8.0\\Academia.WebRentas.WebApi.AssemblyInfo.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\obj\\Debug\\net8.0\\Academia.WebRentas.WebApi.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\appsettings.Development.json",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\appsettings.json",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\.gitattributes",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\.gitignore",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\kubernetes\\hn-super-siman\\values.yaml",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\Properties\\launchSettings.json"

5CBF7A03-38D2-46E5-886C-7E136ECD501F.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\.sonarqube\\out\\0"
5CBF7A03-38D2-46E5-886C-7E136ECD501F.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\.sonarqube\\out\\0\\Issues.json"

5CBF7A03-38D2-46E5-886C-7E136ECD501F.sonar.working.directory=C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\.sonarqube\\out\\.sonar\\mod0
56965077-FC0B-4676-AAF4-4226426EEEA1.sonar.projectKey=academia.academia.transporteapi:56965077-FC0B-4676-AAF4-4226426EEEA1
56965077-FC0B-4676-AAF4-4226426EEEA1.sonar.projectName=Rentas.UnitTest
56965077-FC0B-4676-AAF4-4226426EEEA1.sonar.projectBaseDir=C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest
56965077-FC0B-4676-AAF4-4226426EEEA1.sonar.sourceEncoding=utf-8
56965077-FC0B-4676-AAF4-4226426EEEA1.sonar.sources=
56965077-FC0B-4676-AAF4-4226426EEEA1.sonar.tests=\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\ContratoRentaDomainTest.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\DataTest\\ContratosRentaTest\\ActualizarTest.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\DataTest\\ContratosRentaTest\\ContratoRentaTest.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\DataTest\\SucursalesTest\\SucursalTest.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\SucursalDomainTest.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\UnitTest1.cs",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\Academia.WebRentas.WebApi_Colaborador.html",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\Academia.WebRentas.WebApi_ContratoRenta.html",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\Academia.WebRentas.WebApi_ContratoRentaDomain.html",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\Academia.WebRentas.WebApi_ContratoRentaDomainRequirement.html",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\Academia.WebRentas.WebApi_Documento.html",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\Academia.WebRentas.WebApi_LogSincronizacion.html",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\Academia.WebRentas.WebApi_Moneda.html",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\Academia.WebRentas.WebApi_PaginacionHelper.html",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\Academia.WebRentas.WebApi_PagoRenta.html",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\Academia.WebRentas.WebApi_Proveedor.html",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\Academia.WebRentas.WebApi_Servicio.html",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\Academia.WebRentas.WebApi_Sucursal.html",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\Academia.WebRentas.WebApi_SucursalDomain.html",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\Academia.WebRentas.WebApi_SucursalDomainRequirement.html",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\Academia.WebRentas.WebApi_TasaDeCambio.html",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\Academia.WebRentas.WebApi_TipoDocumento.html",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\class.js",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_cog.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_cog_dark.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_cube.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_cube_dark.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_fork.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_fork_dark.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_info-circled.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_info-circled_dark.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_minus.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_minus_dark.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_plus.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_plus_dark.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_search-minus.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_search-minus_dark.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_search-plus.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_search-plus_dark.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_sponsor.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_star.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_star_dark.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_up-dir.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_up-dir_active.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_up-down-dir.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_up-down-dir_dark.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_wrench.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\icon_wrench_dark.svg",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\index.htm",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\index.html",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\main.js",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage-report\\report.css",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage.cobertura.xml",\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Rentas.UnitTest\\coverage.json"

56965077-FC0B-4676-AAF4-4226426EEEA1.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\.sonarqube\\out\\1"
56965077-FC0B-4676-AAF4-4226426EEEA1.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\.sonarqube\\out\\1\\Issues.json"

56965077-FC0B-4676-AAF4-4226426EEEA1.sonar.working.directory=C:\\Users\\cjpineda\\Desktop\\Ejercicios c#\\ProyectoAcademia\\Academia.WebRentas.WebApi\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=https://sonarqube.grupofarsiman.io/
sonar.visualstudio.enable=false

sonar.modules=5CBF7A03-38D2-46E5-886C-7E136ECD501F,56965077-FC0B-4676-AAF4-4226426EEEA1

